### ISSUE TITLE
[Hover Ruler] button does not show up

### ISSUE THREAD

**Issue by Kazzz-S** [s910324/HoverRulerPlugin#1]
Thanks for the outstanding contribution: https://www.klayout.de/forum/discussion/comment/10612/#Comment_10612 

I have downloaded a ZIP from this repository and unpacked it, as shown below.
![1](https://github.com/s910324/HoverRulerPlugin/assets/16847255/cd51cf00-b6bd-446c-88ca-c98b597205ce)

So far, my **salt** directory contains ...
![2](https://github.com/s910324/HoverRulerPlugin/assets/16847255/33f21f63-735a-43c1-8965-961cc5739e23)

**CenterRulerPlugin** button shows up, but **HoverRulerPlugin** doesn't.
![3](https://github.com/s910324/HoverRulerPlugin/assets/16847255/84f20624-2216-4374-92f4-06f0eaf06b52)

The problem reproduces in my Windows 10 and macOS.
Any suggestions?

Regards,
Kazzz-S

**Comment by s910324** [comment]
Hi Kazzz, 

It seems like I've missed one *.py package which leads to import error during plugin initiallization.

I've update the package, the app should be able to show up correctly.

Thankys.

**Comment by Kazzz-S** [comment]
Hi @s910324,

Thanks for fixing the issue promptly.
Now it works fine!

https://github.com/s910324/HoverRulerPlugin/assets/16847255/c3e70e30-de17-4909-8b15-2e027956df3d

Kazzz-S
